#include "pcheader.h"
#include "Components.h"

namespace OverEngine
{
	OE_REFLECT_STRUCT_BEGIN(NameComponent)
	OE_REFLECT_STRUCT_MEMBER(Name)
	OE_REFLECT_STRUCT_END()

	OE_REFLECT_STRUCT_BEGIN(SpriteRendererComponent)
	OE_REFLECT_STRUCT_MEMBER(Tint)
	OE_REFLECT_STRUCT_MEMBER(Tiling)
	OE_REFLECT_STRUCT_MEMBER(Offset)
	OE_REFLECT_STRUCT_MEMBER(Flip)
	OE_REFLECT_STRUCT_MEMBER(ForceTile)
	OE_REFLECT_STRUCT_END()
}
